server:
  port: 18082
spring:
  application:
    name: canal
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix配置
hystrix:
  commond:
    default:
      execution:
        timeout:
          #如果enable设置为false,则请求超时交给ribbon控制
          enable: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  client:
    instances:
      example:
        host: 192.168.42.136
        port: 11111
