spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #id是唯一标识符
        - id: changgou_goods_route
          #用户请求需要路由到该服务
          #uri: http://localhost:18081
          #将uri替换成lb+服务名称，就可以负载均衡了，是不是很强..lb表示LoadBalanacerClient,主要用于集群
          uri: lb://goods
          predicates:
            #host过滤，也可以用下面的路劲过滤path
            #- host=cloud.itheima.com
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
            #- Path=/goods/**
          filters:
            #- PrefixPath=/brand
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                #用户身份唯一标识符
                key-resolver: "#{@ipKeyResolver}"
                #每秒钟只允许有1个请求
                redis-rate-limiter.replenishRate: 1
                #允许并发有四个请求【宽限的个数】
                redis-rate-limiter.burstCapacity: 1
          #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
      #订单微服务
        - id: changgou_order_route
        uri: lb://order
        predicates:
          - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
        filters:
          - StripPrefix=1
          #认证微服务
        - id: changgou_oauth_user
          uri: lb://user-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true